### ISSUE TITLE
Dock missing from Watney 2.0 STLs

### ISSUE THREAD

**Issue by rtaylo** [nikivanov/watney#28]
would you be able to post the dock STL for the 2.0 version of Watney? I have to reprint it.
(I'm also waiting on some part to build my 3.0 version, can't wait!)

**Comment by nikivanov** [comment]
Oh wow, I never noticed that the dock was missing. I'll upload it in a few days and link you to it.

**Comment by rtaylo** [comment]
Awesome! Thanks. I just needed to reprint it and modify it some. I'm using
a different wireless charger and need a bit more space underneath.

**Comment by nikivanov** [comment]
Hey @rtaylo I've uploaded the missing dock files. Since you're going to be modifying the dock, I figured you might want the STEP file, so here are both the STL and STEP files for the dock:

https://github.com/nikivanov/watney/blob/watney2_0_dock/STLs/dock.stl
https://github.com/nikivanov/watney/blob/watney2_0_dock/STLs/dock%20v11.step

**Comment by rtaylo** [comment]
Awesome! Thanks mate. I need to post a picture as well of my Watney garage.

(Building my 3.0 soon)
